### ISSUE TITLE
Giver's insignias (linen and silk) have incorrect recipe names

### ISSUE THREAD

**Issue by BenLubar** [xanthics/gw2craft#27]
`Giver's Embroidered {Linen,Silk} Insignia` is taught by `Recipe: Giver's Intricate {Linen,Silk} Insignia`. Not technically a bug in gw2craft, but it confused me when I was trying to level leatherworking. Maybe put a note next to anywhere those two insignias need to be made?

**Comment by xanthics** [comment]
Forgot to close this when issue was fixed.
