### ISSUE TITLE
Request: Update the projected cost when API Key is inserted

### ISSUE THREAD

**Issue by Rushleader** [xanthics/gw2craft#34]
When loading the API Key parse the already possessed mats and subtract that from the projected cost so you have an indication what your cost is

**Comment by TomKriek** [comment]
@xanthics is it okay if I try and make a jQuery function which recalculates the total cost when amount are being changed via API update or input element changes? I might have to pull some data to the front since you already format the amount in xxg xxs xxc should be fairly easy to make this dynamic.

**Comment by xanthics** [comment]
@TomKriek You certainly can.  I can also put the raw copper price per item as a field somewhere, if that makes it easier.

**Comment by TomKriek** [comment]
Yeah that would be perfect, I saw you using a single variable for the amount of copper for the items. If you could place that somewhere around the "Have" "Need" with a class.

Something along the lines of
```
<span style="display:none;" class="coins">[copper_amount]</span>
```

**Comment by xanthics** [comment]
I've added a raw_copper field that can have values of 0 or higher to all of the cells that have the field data-need="more|done"

    <input type="number" id="19699bv" value='72' raw_copper='264' readonly data-need = "more" min="0" />

**Comment by TomKriek** [comment]
Perfect, I have time this weekend to work on the recalculation of the total cost. Thanks for the update.

**Comment by TomKriek** [comment]
@xanthics  I'll be able to wrap up the function for recalculating upcoming Wednesday. Would it be possible by any chance to get more of those raw copper fields on the Sell List items? I will be able to update the full Initial Cost + Expected Recovery and Expected Final Cost with those extra fields.

**Comment by xanthics** [comment]
@TomKriek Got distracted and forgot to reply.  Why would those items need fields?  I can add one for the expected recovery field, but the other ones shouldn't need it.

**Comment by xanthics** [comment]
Should be fixed now.
