### ISSUE TITLE
Error running Create_recipes.py

### ISSUE THREAD

**Issue by Marthisdil** [xanthics/gw2craft#36]
Both with windows and linux, getting the following errors when trying to run Create_Recipes.py:

jason@mint-vm ~/Desktop/gw2craft $ pypy Create_recipes.py
Traceback (most recent call last):
  File "Create_recipes.py", line 294, in <module>
    main()
  File "Create_recipes.py", line 281, in main
    recipes = get_recipes()
  File "Create_recipes.py", line 54, in get_recipes
    procs = [p.map(recipelistWorker, [lister[i:i + 200] for i in range(0, len(lister), 200)])]
TypeError: 'slice' objects are unhashable

Exact same error regardless of Windows or Linux

**Comment by xanthics** [comment]
{u'text': u'API not active'}

Not a bug with the code, the API endpoint is currently inactive.

**Comment by xanthics** [comment]
https://en-forum.guildwars2.com/discussion/3195/api-temporarily-disabled
