### ISSUE TITLE
Issue running Crafting.pypy

### ISSUE THREAD

**Issue by Marthisdil** [xanthics/gw2craft#37]
Regardless of Windows or Linux - getting the same error:

jason@mint-vm ~/Desktop/gw2craft $ pypy Crafting.py
Start: main
Start: costs
ERROR: HTTP Error 503: Service Unavailable.
ERROR: HTTP Error 503: Service Unavailable.
ERROR: HTTP Error 503: Service Unavailable.
ERROR: HTTP Error 503: Service Unavailable.
^C  End: costs, took 21.013 seconds
  End: main, took 21.017 seconds
Traceback (most recent call last):
  File "Crafting.py", line 151, in <module>
    main()
  File "Crafting.py", line 88, in main
    cList = appendCosts()
  File "/home/jason/Desktop/gw2craft/MyPrices.py", line 143, in appendCosts
    time.sleep(randint(1, 10))
KeyboardInterrupt

Internet is working fine on all computers.

**Comment by xanthics** [comment]
{u'text': u'API not active'}

Not a bug with the code, the API endpoint is currently inactive.
