### ISSUE TITLE
get an ssl cert

### ISSUE THREAD

**Issue by xanthics** [xanthics/gw2craft#40]
In order to enable https

**Comment by PaxJaromeMalues** [comment]
I see you now have one via lets encrypt, thumbs up for using their service.
There is an option when using this service with certbot that will redirect all traffic to the ssl secured site so all http requests will be forwarded to https. That would be a good idea to do.

**Comment by xanthics** [comment]
Forgot to put flipping the switch on my todo list.  There was some initial hiccups with serving via https so I didn't force it.  Should be forced now, will see if I get any broken experiences.
