### ISSUE TITLE
Lots of over- & underproduction

### ISSUE THREAD

**Issue by PaxJaromeMalues** [xanthics/gw2craft#41]
A lot of items are crafted even though not required for any recepies, other recepies do not sum up properly to the amoput required over an entire Tier.
I used the amorcraft one (with api option) and as an example it told me for Tier2 to craft 42 woolballs, but then reuired me to manually craft more to complete some insignias for the steps below. A bit confusing. Am I using the tool wrong by any chance?

**Comment by PaxJaromeMalues** [comment]
btw its the normal guide I am using

**Comment by PaxJaromeMalues** [comment]
Reference: Tier 2 at level 125 finished
Ive got quite some unused stuff left and quite some stuff missing until 150.
![gw2crafts1](https://user-images.githubusercontent.com/12395410/57986951-90c66d00-7a7b-11e9-9c4c-8b3dc497751f.jpg)
![gw2crafts2](https://user-images.githubusercontent.com/12395410/57986952-90c66d00-7a7b-11e9-96ac-d6a3a0bf2b2a.jpg)

**Comment by xanthics** [comment]
Tier 2 is 75 - 150, it doesn't stop at 125

Looking at a current iteration of the normal armorcrafting guide (2019-05-22T19:00:05+00:00)

subparts:
11 helm sets (1 casing purchased)
7 pauldron sets (5 casing and 1 lining purchased)
4 boot sets
3 armguard sets

finished craft:
Helm: 75, 100, 100, 100, 100, 125, 125, 125, 125, 125, 125 = 11
Pauldron: 75, 75, 100, 100, 100, 100, 125 = 7
Boot: 100, 100, 100, 125 = 4
Armguard(Gauntlet): 100, 100, 125 = 3

![image](https://user-images.githubusercontent.com/3137623/58201678-8201d500-7c8a-11e9-8cea-2470830dd86b.png)
