### ISSUE TITLE
Chef 500?

### ISSUE THREAD

**Issue by kazerniel** [xanthics/gw2craft#42]
ANet has added it:
https://wiki.guildwars2.com/wiki/Game_updates/2019-08-27#General

**Comment by xanthics** [comment]
ANet went a different direction with chef 401+.  Basically you want to get to 440/450 and then do the in game questing to finish off to 500 while also enabling new drops.  There are guides being generated to get to 450 but the best choice is to make a bunch of something such as https://wiki.guildwars2.com/wiki/Cup_of_Light-Roasted_Coffee

**Comment by kazerniel** [comment]
Thanks!
