### ISSUE TITLE
Suggestion: auto copy with 1 click

### ISSUE THREAD

**Issue by SullieLore** [xanthics/gw2craft#46]
Hello!

I use this guide weekly: https://gw2crafts.net/cooking_karma_fast_200.html

Very helpful. However, it would be improved if there was an auto copy function after each ingredient. This would allow quicker copy and paste into the trading post/recipe list in-game.

Sullie

**Comment by xanthics** [comment]
Added the following css styles and selectors.  It's not quite 1 click, but it makes selecting text a lot easier.

```.select_text {
    -webkit-user-select: all; /* Safari */
    -ms-user-select: all; /* IE 10+ and Edge */
    -moz-user-select: all; /* Firefox */
    user-select: all; /* Standard syntax */
    cursor: pointer;}

**Comment by SullieLore** [comment]
Very nice. Thanks for the quick action!
