### ISSUE TITLE
Intermediate crafts don't correctly account for output_item_count

### ISSUE THREAD

**Issue by TheSnook** [xanthics/gw2craft#50]
Example: In the F2P Leatherworker guide at lvl 200 it says "Make: 7 Cotton Patch", and indeed 7 patches are required to make the Insignias in the guide at this level. The Cotton Patch recipe produces 5 items per craft, so only 2 crafting iterations are necessary to get 7 patches, but the shopping list says to buy enough leather, cotton, and thread for 7 crafting iterations.

Is this a bug, or is it actually optimal to over-craft the patches by 5x and the 7 crafts vs 7 required items is just a coincidence?

**Comment by xanthics** [comment]
I'd swear that recipe used to only produce 1 output, but I never tracked those.  That's a bug and I'll take a look at it this weekend.

**Comment by xanthics** [comment]
Work got in the way but I have more time to focus on this now.  I think I know how I want to fix this and hope to have a fix by Monday.  Basically multi-output recipes will be treated like bronze ingots.

**Comment by xanthics** [comment]
Still working on this.  Having to rewrite more code than expected due to decisions when i first wrote the code.  EG lists being multiplied by number of items in a recipe, which was always in int before and can now be a float < 1.

**Comment by xanthics** [comment]
Should be resolved with 618de59f3662a6367ef9c20a3d60bbba6afbf123 but please let me know if you notice any other issues
