### ISSUE TITLE
Random characters in upper left corner

### ISSUE THREAD

**Issue by Svish** [xanthics/gw2craft#52]
Probably not intentional? 🙃

![image](https://user-images.githubusercontent.com/142162/106743928-4a35ef00-661f-11eb-9318-27b0223f7343.png)

**Comment by xanthics** [comment]
That's some characters to `terminate` a javascript command that are instead somewhere they are being interpreted as text.  Looks like the fallback I had to add jQuery from ms if google failed is the culprit.  This is fixed now and should start appearing in new guides.
