### ISSUE TITLE
[Scribe] Centaur Banner not available at level 250

### ISSUE THREAD

**Issue by rafaelgsilveira** [xanthics/gw2craft#55]
As per the Scribing Guide, at level 250 I should make 28 Centaur Banner (WvW Claiming Item, namely "Schematic: Centaur Banner").
I am currently a level 252 Scribe and I can't see the the recipe.  I have tried to "discover" the recipe as well, but the components won't even show in the dicover tab.

Furthermore, the Wiki also states that is IS a level 250 recipe.

I am guessing this should have changed in the last update (3rd expansion).

Anyway, as Scribing is very expensive to level up, I wanted to point it out.

I am available if any clarification is needed.

![gw022_mod](https://user-images.githubusercontent.com/25122573/160023810-f85f3551-48b0-434c-97f0-cebd90cadb77.jpg)

Ty

**Comment by xanthics** [comment]
Requires a guild upgrade `Acquiring this guild upgrade unlocks the recipe to craft [Schematic: Centaur Banner](https://wiki.guildwars2.com/wiki/Schematic:_Centaur_Banner). Available only to [scribes](https://wiki.guildwars2.com/wiki/Scribe).`

https://wiki.guildwars2.com/wiki/Scribing:_Centaur_Banner

Does the guild you are in have that upgrade?

**Comment by rafaelgsilveira** [comment]
Yep, you're absolutely right. I'm sorry about that.
I visited another guid hall and I can see the item to be crafted. Ty!
