### ISSUE TITLE
Normal Cooking Guide advises use of unavailable recipe

### ISSUE THREAD

**Issue by Corolin112** [xanthics/gw2craft#57]
I was following the Normal Cooking Guide with Top 5 Hearts enabled. For 125-150 it advised I make Fried Banana Chips. I looked through the wiki and it does not appear that the recipe for Fried Banana Chips is available to buy unless the event Festival of the Four Winds is currently running, so I was not able to follow that section of the guide

**Comment by xanthics** [comment]
Fixed, thank you for the report. 85e9d97c793516dfbb9cfa849498fa2c78fa5e89
