### ISSUE TITLE
Armorsmith 400-500 doesn't include the linseed oil

### ISSUE THREAD

**Issue by arakielG** [xanthics/gw2craft#58]
You need 5 linseed oil for each of the Orichalcum components.  At current market prices that works out to an additional 122 gold!  I wouldn't have bought everything else if I had known that

**Comment by arakielG** [comment]
...oiled ones do.  im stupid

**Comment by xanthics** [comment]
You aren't the first to contact me about the oiled parts.  It sounds like the in game ui might be a bit misleading.
