### ISSUE TITLE
Crafting lvl 1-400 Weaponsmith

### ISSUE THREAD

**Issue by CrimzonDragonz** [xanthics/gw2craft#62]
So i got stuck at lvl 60 from your guide, i didnt reach lvl 75 mark, so i just wanted to inform you this guide is faulty

**Comment by CrimzonDragonz** [comment]
it might just have been updated

**Comment by xanthics** [comment]
Guides update once per hour, and recipes are controlled from the API.  If you have a timestamp, all guides are archived for 3 months, it would allow a closer look.  Also there are fast and normal guides, and f2p and normal variants.

https://gw2crafts.net/archive/20221127T1100/weaponcraft.html

https://gw2crafts.net/archive/20221127T1100/weaponcraft_fast.html
