### ISSUE TITLE
Jewelcrafting "normal guide" not generating full suggested steps

### ISSUE THREAD

**Issue by Antagonizing** [xanthics/gw2craft#65]
Jewelcrafting is only suggesting partial steps. Between 275-300 it asked me to create 9 Embellished Ornate Emerald Jewel and nothing else leaving me at 283.

This would throw off the suggested purchase list and estimated cost as well.

![image](https://user-images.githubusercontent.com/34669551/232285958-748df2fc-8268-4eb4-b8c6-d43fdb4c4632.png)

**Comment by xanthics** [comment]
based on the skill level you ended up on, you made the wrong rarity of jewel.  Masterwork instead of rare.  They use essentially the same ingredients so it's easy to realize too late.

**Comment by Antagonizing** [comment]
Yep you're correct. I must've been very tired. Sorry for the incorrect report and I appreciate the swift response!
